ViewCommand=
FileNameSource=CubeOctahedron.c
FileNameBinary=CubeOctahedron.ihx
Engine=0
Memory=1
Command=-mmcs51 --model-large --code-loc 0x%CODELOC%00 --code-size 0x%CODESIZE%00 --xram-loc 0x%DATALOC%00 --xram-size 0x%DATASIZE%00
MemCodeLoc=03
MemCodeSize=7D
MemDataLoc=80
MemDataSize=80
MemSwapLoc=02
LibraryFiles=core.h|console.h|spreadsheet.h|graph.h|mathx.h
Description="Draws cube on Graph 0 and Octahedron on Graph 1."
