ViewCommand=
FileNameSource=Thread1.c
FileNameBinary=Thread1.ihx
Engine=0
Memory=1
Command=-mmcs51 --model-large --code-loc 0x%CODELOC%00 --code-size 0x%CODESIZE%00 --xram-loc 0x%DATALOC%00 --xram-size 0x%DATASIZE%00
MemCodeLoc=03
MemCodeSize=7D
MemDataLoc=80
MemDataSize=80
MemSwapLoc=02
LibraryFiles=core.h|console.h|bundle.h
Description="Thread demo - load Thread1.sdc to 0 item and Thread2.sdc to 1, compile both items and run 0 item (Thread1.sdc) to print text on Console 0."
